# Generated by Django 4.2.4 on 2023-09-04 11:24

from django.db import migrations, models
import django_fileupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fileupload', '0004_rename_hash_fileupload_checksum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=django_fileupload.models.FileUploadFileStorage(), upload_to=django_fileupload.models._generate_complete_file_path),
        ),
    ]
