# Generated by Django 4.2.5 on 2023-09-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_fileupload', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='mime_type',
            new_name='detected_mime_type',
        ),
    ]
