# Generated by Django 5.0 on 2024-07-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fileupload", "0007_alter_fileuploadbatch_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="deleted_on",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
