# Generated by Django 5.0.1 on 2024-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='ok',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
