name: Documentation deployment workflow

on:
  push:
    branches:
      - main
    paths:
      - docs/**/*
  pull_request:
    branches:
      - main
    paths:
      - docs/**/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Deploying the docs
        run: |
          echo "Deploying the docs"
          curl --request POST ${{ secrets.ACINT_URL }} -H "Content-Type: application/json" -d "{\"action\": \"${{ secrets.ACINT_ACTION }}\", \"token\": \"${{ secrets.ACINT_TOKEN }}\"}"
